/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    AdvanceSetting: typeof import('./src/components/setting/basic/AdvanceSetting.vue')['default']
    AllAccount: typeof import('./src/components/setting/account/AllAccount.vue')['default']
    AMLyric: typeof import('./src/components/player/AMLyric.vue')['default']
    BasicSetting: typeof import('./src/components/setting/basic/BasicSetting.vue')['default']
    CommonLyric: typeof import('./src/components/player/CommonLyric.vue')['default']
    CommonSongItem: typeof import('./src/components/search/CommonSongItem.vue')['default']
    ContextMenu: typeof import('./src/components/common/ContextMenu.vue')['default']
    ControlPanel: typeof import('./src/components/player/ControlPanel.vue')['default']
    DialogWrapper: typeof import('./src/components/common/DialogWrapper.vue')['default']
    ElectronOperation: typeof import('./src/components/ElectronOperation.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    KGLogin: typeof import('./src/components/setting/account/KGLogin.vue')['default']
    KGRecommendPlaylist: typeof import('./src/components/playList/KGRecommendPlaylist.vue')['default']
    KGRecommendSong: typeof import('./src/components/playList/KGRecommendSong.vue')['default']
    LoginCard: typeof import('./src/components/home/LoginCard.vue')['default']
    LyricSetting: typeof import('./src/components/setting/lyric/LyricSetting.vue')['default']
    MainPlayer: typeof import('./src/components/player/MainPlayer.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PlayControlBtn: typeof import('./src/components/player/PlayControlBtn.vue')['default']
    PlayerBackground: typeof import('./src/components/player/PlayerBackground.vue')['default']
    PlayerBar: typeof import('./src/components/player/PlayerBar.vue')['default']
    Playing: typeof import('./src/components/playList/Playing.vue')['default']
    PlaylistCollect: typeof import('./src/components/list/PlaylistCollect.vue')['default']
    PlayListDetailLayout: typeof import('./src/components/playList/PlayListDetailLayout.vue')['default']
    PlaylistList: typeof import('./src/components/playList/PlaylistList.vue')['default']
    PlaySequence: typeof import('./src/components/player/PlaySequence.vue')['default']
    ProgressPanel: typeof import('./src/components/player/ProgressPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SequenceItem: typeof import('./src/components/player/SequenceItem.vue')['default']
    SongItem: typeof import('./src/components/playList/songItem.vue')['default']
    SongList: typeof import('./src/components/list/SongList.vue')['default']
    TipsHistory: typeof import('./src/components/search/TipsHistory.vue')['default']
    VolumePanel: typeof import('./src/components/player/VolumePanel.vue')['default']
    WelcomeCard: typeof import('./src/components/home/WelcomeCard.vue')['default']
    WYLogin: typeof import('./src/components/setting/account/WYLogin.vue')['default']
  }
}
